### ISSUE TITLE
Add SCIP support

### ISSUE THREAD

**Issue by matbesancon** [rust-or/good_lp#11]
SCIP is one of the commonly-used MI(N)LP solvers and could be of interest to the rust-or communities (free and source available for academic use).

I'd be willing to help add it to lp-solvers if this is the appropriate repository

**Comment by mmghannam** [comment]
Hi! I am working on a rust interface for SCIP https://github.com/mmghannam/russcip. It has basic MIP-solving functionality now, it can add variables and constraints. It would be great if you could tell me the next steps to plug it into the `good_lp` API, more specifically which traits and functions do I need to implement.  Thanks a lot!

**Comment by lovasoa** [comment]
Great news @mmghannam !

You should create a new file in the src/solvers directory, and add a new feature flag to this library. You can start from one of the existing solvers as an example (I think minilp is the best to take as an example because it's tiny and simple). The main thing to do is to write an `scip` function that takes an `UnsolvedProblem` and returns a custom struct that wraps an scip model object. Then you have to implement `SolverModel` on it.

**Comment by mmghannam** [comment]
Thanks! that's very helpful. I will work on it and add a pull request soon.

**Comment by jacobsvante** [comment]
Should this be closed?
